package com.btface.greendaodemo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.botian.recognition.bean.CheckFaceHistory;

import com.btface.greendaodemo.CheckFaceHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig checkFaceHistoryDaoConfig;

    private final CheckFaceHistoryDao checkFaceHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        checkFaceHistoryDaoConfig = daoConfigMap.get(CheckFaceHistoryDao.class).clone();
        checkFaceHistoryDaoConfig.initIdentityScope(type);

        checkFaceHistoryDao = new CheckFaceHistoryDao(checkFaceHistoryDaoConfig, this);

        registerDao(CheckFaceHistory.class, checkFaceHistoryDao);
    }
    
    public void clear() {
        checkFaceHistoryDaoConfig.clearIdentityScope();
    }

    public CheckFaceHistoryDao getCheckFaceHistoryDao() {
        return checkFaceHistoryDao;
    }

}
